# Generated by Django 5.1.2 on 2024-10-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fk_genero',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
    ]
